## EmailMarketing.Domain.Entity.Campanha.dcm.yml
EmailMarketing\Domain\Entity\Campanha:
    type: entity
    repositoryClass: EmailMarketing\Infrastructure\Persistence\Doctrine\Repository\CampanhaRepository
    table: campanhas
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields: 
        nome:
            type: string
            length: 255
        template:
            type: text
    manyToMany:
        tags:
            targetEntity: EmailMarketing\Domain\Entity\Tag
            mappedBy: campanhas
            joinTable:
                name: campanhas_tags
                joinColumns:
                    campanha_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id